# Generated by Django 4.2.11 on 2024-04-02 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=500)),
                ('payroll_frequency', models.CharField(choices=[('weekly', 'WEEKLY'), ('bi-weekly', 'BIWEEKLY'), ('unknown', 'UNKNOWN')], max_length=100)),
                ('payroll_receive_method', models.CharField(choices=[('API', 'API'), ('SFTP', 'SFTP')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccountStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Implementation', 'Implementation'), ('Active', 'Active'), ('Deactivated', 'Deactivated')], max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('pay_start', models.DateField()),
                ('pay_end', models.DateField()),
                ('gross_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('base_wages', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('overtime_wages', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('other_wages', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('gross_wages', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('bonus_wages', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('commission_wages', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('incentive_wages', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('custom_wages', models.JSONField(default=dict, help_text='Additional non-standard wages')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership_started', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.partner')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='account_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accountstatus'),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.accounttype'),
        ),
    ]
