# Generated by Django 4.2.11 on 2024-04-02 21:39
from django.db import migrations
import os

from django.db import migrations


def create_interview_data(apps, schema_editor):
    AccountStatus = apps.get_model('accounts', 'AccountStatus')
    AccountType = apps.get_model('accounts', 'AccountType')
    Account = apps.get_model('accounts', 'Account')
    Partner = apps.get_model('accounts', 'Partner')
    PartnerAccount = apps.get_model('accounts', 'PartnerAccount')
    Payroll = apps.get_model('accounts', 'Payroll')

    # Create AccountStatus objects
    AccountStatus.objects.create(
        name='Active',
    )
    AccountStatus.objects.create(
        name='Deactivated',
    )
    AccountStatus.objects.create(
        name='Implementation',
    )

    # Create AccountType objects
    AccountType.objects.create(
        name='Client',
    )
    AccountType.objects.create(
        name='Partner',
    )

    # Create Account objects
    Account.objects.create(
        name='Hospital Account',
        payroll_frequency='bi-weekly',
        payroll_receive_method='SFTP',
        account_type_id=1,
        account_status_id=1,
    )
    Account.objects.create(
        name='Bank Account',
        payroll_frequency='weekly',
        payroll_receive_method='API',
        account_type_id=1,
        account_status_id=1,
    )

    # Create Partner objects
    Partner.objects.create(
        name='Partner 1',
    )

    # Create PartnerAccount objects
    PartnerAccount.objects.create(
        partner_id=1,
        account_id=1,
        partnership_started='2024-04-02',
    )

    # Create Payroll objects
    Payroll.objects.create(
        account_id=1,
        check_date='2024-04-02',
        pay_start='2024-04-02',
        pay_end='2024-04-17',
        gross_hours=80.0,
        base_wages=1000.0,
        gross_wages=1000.0,
    )
    Payroll.objects.create(
        account_id=1,
        check_date='2024-04-17',
        pay_start='2024-04-17',
        pay_end='2024-05-02',
        gross_hours=80.0,
        base_wages=1000.0,
        gross_wages=1000.0,
    )
    Payroll.objects.create(
        account_id=2,
        check_date='2024-04-02',
        pay_start='2024-04-02',
        pay_end='2024-04-17',
        gross_hours=80.0,
        base_wages=1000.0,
        overtime_wages=500.0,
        gross_wages=1500.0,
    )


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_interview_data),
    ]
